import pytest
from robotsix_mill.cli import main
from robotsix_mill.cli._parser import build_parser
from robotsix_mill.core.states import State


def test_build_parser_returns_parser():
    """``build_parser()`` returns an ArgumentParser with expected subcommands."""
    parser = build_parser()
    # Spot-check that key subcommands are registered.
    assert hasattr(parser, "parse_args")
    # --print-completion is registered on the parser.
    actions = {a.dest for a in parser._actions}
    assert "print_completion" in actions


def test_print_completion_bash_exits_zero():
    """``main([\"--print-completion\", \"bash\"])`` exits 0 and prints a script."""
    pytest.importorskip("shtab")
    import io
    import sys

    old_stdout = sys.stdout
    try:
        sys.stdout = io.StringIO()
        rc = main(["--print-completion", "bash"])
        output = sys.stdout.getvalue()
    finally:
        sys.stdout = old_stdout

    assert rc == 0
    # shtab output always contains this marker.
    assert "AUTOMATICALLY GENERATED by `shtab`" in output
    assert "bash" in output.lower() or "_shtab_" in output


def test_print_completion_zsh_exits_zero():
    """``main([\"--print-completion\", \"zsh\"])`` exits 0 and prints a script."""
    pytest.importorskip("shtab")
    import io
    import sys

    old_stdout = sys.stdout
    try:
        sys.stdout = io.StringIO()
        rc = main(["--print-completion", "zsh"])
        output = sys.stdout.getvalue()
    finally:
        sys.stdout = old_stdout

    assert rc == 0
    assert "AUTOMATICALLY GENERATED by `shtab`" in output


def test_approve_success(settings, service, repos_registry):
    """CLI `ticket approve <id>` exits 0 on success with human-readable output."""
    t = service.create("Approve me via CLI")
    service.transition(t.id, State.HUMAN_ISSUE_APPROVAL, note="refined")

    # Override api_url so the CLI hits the test server instead of localhost.
    # We can't easily run the full server in a CLI test, so we test the
    # client-side logic by mocking httpx. But the CLI uses a real HTTP
    # client — we need the server running. For a pure unit test, let's
    # run the server via TestClient and set api_url accordingly.
    from fastapi.testclient import TestClient
    from robotsix_mill.runtime.api import create_app

    with TestClient(create_app(repos_registry, settings, single_repo_id="test-repo")):
        # The CLI uses settings.api_url to reach the server.
        # We can't override that easily without monkeypatching.
        pass

    # Instead, we test the approve logic directly via the API and just
    # verify the CLI argument parsing exits correctly for the success case.
    # The full integration test requires the server to be running.
    # For this test, we'll use httpx mocks.

    import httpx

    class FakeResponse:
        def __init__(self, status_code, json_data):
            self.status_code = status_code
            self._json = json_data
            self.text = ""

        def json(self):
            return self._json

        @property
        def is_success(self):
            return 200 <= self.status_code < 300

        def raise_for_status(self):
            if not self.is_success:
                raise httpx.HTTPStatusError("", request=None, response=self)

    class FakeClient:
        def __init__(self, *args, **kwargs):
            pass

        def __enter__(self):
            return self

        def __exit__(self, *args):
            pass

        def post(self, url, **kwargs):
            if url.endswith("/approve"):
                return FakeResponse(
                    200,
                    {"id": "test-id", "state": "ready", "title": "T"},
                )
            return FakeResponse(404, {})

    # patch httpx.Client with our fake
    import robotsix_mill.cli as cli_mod

    original = cli_mod.httpx.Client
    cli_mod.httpx.Client = FakeClient
    try:
        rc = main(["ticket", "approve", "test-id"])
        assert rc == 0
    finally:
        cli_mod.httpx.Client = original


def test_approve_failure(settings, service):
    """CLI `ticket approve <id>` exits non-zero on failure (e.g. 409)."""
    import httpx
    import robotsix_mill.cli as cli_mod

    class FakeResponse:
        def __init__(self, status_code, detail):
            self.status_code = status_code
            self._detail = detail
            self.text = ""

        def json(self):
            return {"detail": self._detail}

        @property
        def is_success(self):
            return 200 <= self.status_code < 300

        def raise_for_status(self):
            if not self.is_success:
                raise httpx.HTTPStatusError("", request=None, response=self)

    class FakeClient:
        def __init__(self, *args, **kwargs):
            pass

        def __enter__(self):
            return self

        def __exit__(self, *args):
            pass

        def post(self, url, **kwargs):
            return FakeResponse(
                409,
                "draft -> ready not allowed",
            )

    original = cli_mod.httpx.Client
    cli_mod.httpx.Client = FakeClient
    try:
        rc = main(["ticket", "approve", "bad-id"])
        assert rc == 1  # non-zero exit
    finally:
        cli_mod.httpx.Client = original


# --- resume-blocked CLI tests ---


def test_resume_blocked_success(settings, service):
    """CLI `ticket resume-blocked <id>` exits 0 on success."""
    import robotsix_mill.cli as cli_mod

    class FakeResponse:
        def __init__(self, status_code, json_data):
            self.status_code = status_code
            self._json = json_data
            self.text = ""

        def json(self):
            return self._json

        @property
        def is_success(self):
            return 200 <= self.status_code < 300

        def raise_for_status(self):
            if not self.is_success:
                raise cli_mod.httpx.HTTPStatusError("", request=None, response=self)

    class FakeClient:
        def __init__(self, *args, **kwargs):
            pass

        def __enter__(self):
            return self

        def __exit__(self, *args):
            pass

        def post(self, url, **kwargs):
            if url.endswith("/resume-blocked"):
                return FakeResponse(
                    200,
                    {"id": "test-id", "state": "done", "title": "T"},
                )
            return FakeResponse(404, {})

    original = cli_mod.httpx.Client
    cli_mod.httpx.Client = FakeClient
    try:
        rc = main(["ticket", "resume-blocked", "test-id"])
        assert rc == 0
    finally:
        cli_mod.httpx.Client = original


def test_resume_blocked_failure(settings, service):
    """CLI `ticket resume-blocked <id>` exits non-zero on failure (e.g. 409)."""
    import robotsix_mill.cli as cli_mod

    class FakeResponse:
        def __init__(self, status_code, detail):
            self.status_code = status_code
            self._detail = detail
            self.text = ""

        def json(self):
            return {"detail": self._detail}

        @property
        def is_success(self):
            return 200 <= self.status_code < 300

        def raise_for_status(self):
            if not self.is_success:
                raise cli_mod.httpx.HTTPStatusError("", request=None, response=self)

    class FakeClient:
        def __init__(self, *args, **kwargs):
            pass

        def __enter__(self):
            return self

        def __exit__(self, *args):
            pass

        def post(self, url, **kwargs):
            return FakeResponse(409, "cannot resume — not BLOCKED")

    original = cli_mod.httpx.Client
    cli_mod.httpx.Client = FakeClient
    try:
        rc = main(["ticket", "resume-blocked", "bad-id"])
        assert rc == 1  # non-zero exit
    finally:
        cli_mod.httpx.Client = original


def test_copy_paste_registered_in_runners():
    """The copy-paste pass is wired into the generic _RUNNERS dispatch table."""
    from robotsix_mill.cli.admin import _RUNNERS

    entry = _RUNNERS["copy-paste"]
    assert entry["module"] == "runners.periodic_runner"
    assert entry["function"] == "run_copy_paste_pass"
    assert entry["format"] == "memory_drafts"


def test_forge_parity_registered_in_runners():
    """The forge-parity pass is wired into the generic _RUNNERS dispatch table."""
    from robotsix_mill.cli.admin import _RUNNERS

    entry = _RUNNERS["forge-parity"]
    assert entry["module"] == "runners.periodic_runner"
    assert entry["function"] == "run_forge_parity_pass"
    assert entry["format"] == "memory_drafts"


def test_copy_paste_cli_command(monkeypatch):
    """`main(["copy-paste"])` dispatches into the runner and exits 0."""
    from robotsix_mill.runners.periodic_runner import CopyPastePassResult

    def mock_run(session_id=None):
        return CopyPastePassResult(updated_memory="mem", drafts_created=[])

    monkeypatch.setattr(
        "robotsix_mill.runners.periodic_runner.run_copy_paste_pass", mock_run
    )

    assert main(["copy-paste"]) == 0


def test_forge_parity_cli_command(monkeypatch):
    """`main(["forge-parity"])` dispatches into the runner and exits 0."""
    from robotsix_mill.runners.periodic_runner import ForgeParityPassResult

    def mock_run(session_id=None):
        return ForgeParityPassResult(updated_memory="mem", drafts_created=[])

    monkeypatch.setattr(
        "robotsix_mill.runners.periodic_runner.run_forge_parity_pass", mock_run
    )

    assert main(["forge-parity"]) == 0


def test_meta_registered_in_runners():
    """The meta pass is wired into the generic _RUNNERS dispatch table."""
    from robotsix_mill.cli.admin import _RUNNERS

    entry = _RUNNERS["meta"]
    assert entry["module"] == "meta.runner"
    assert entry["function"] == "run_meta_pass"
    assert entry["format"] == "memory_drafts"


def test_meta_cli_command(monkeypatch):
    """`main(["meta"])` dispatches into the runner and exits 0."""
    from robotsix_mill.meta.runner import MetaPassResult

    def mock_run(session_id=None):
        return MetaPassResult(
            updated_memory="mem",
            extraction_drafts_created=[],
            alignment_drafts_created=[],
            todo_drafts_created=[],
        )

    monkeypatch.setattr("robotsix_mill.meta.runner.run_meta_pass", mock_run)

    assert main(["meta"]) == 0


def test_serve_does_not_exit_on_zero_repos(monkeypatch):
    """An empty repos registry must NOT cause _serve() to return 2."""
    import argparse
    import sys
    from unittest.mock import MagicMock

    from robotsix_mill.cli.serve import _serve
    from robotsix_mill.config import ReposRegistry

    empty_repos = ReposRegistry(repos={})
    monkeypatch.setattr(
        "robotsix_mill.config.get_repos_config",
        lambda: empty_repos,
    )

    # Inject a mock uvicorn module so _serve()'s `import uvicorn` gets our mock
    # instead of the real uvicorn (which would try to bind a port).
    mock_uvicorn = MagicMock()
    monkeypatch.setitem(sys.modules, "uvicorn", mock_uvicorn)

    args = argparse.Namespace(repo_id=None)
    result = _serve(args, MagicMock())  # settings is unused by this path

    assert result == 0
    mock_uvicorn.run.assert_called_once()
