.DEFAULT_GOAL := help

.PHONY: help  ## Show this help message
help:
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

# Local development (no Docker). Override the interpreter with
# `make PYTHON=python3 install` if 3.14 isn't on PATH as python3.14.
PYTHON ?= python3.14
VENV   := .venv
BIN    := $(VENV)/bin

SOURCES ?= src/ tests/ scripts/ vulture_whitelist.py deploy/split_config.py dev/

.PHONY: help install test format lint serve dev docker clean docs-serve docs-build migrate completions migration migrate-stamp

$(BIN)/activate:
	$(PYTHON) -m venv $(VENV)

install:  ## Install the package, dependencies, and pre-commit for local development
	uv sync --frozen --extra tracing

test: install  ## Run tests with pytest (coverage ≥ 70%)
	$(BIN)/python -m pytest -q --cov=robotsix_mill --cov-report=term-missing --cov-fail-under=70

format: install  ## Auto-format Python source files
	uv run ruff check --fix $(SOURCES)
	uv run ruff format $(SOURCES)

lint: install  ## Lint Python source files (check only)
	uv run ruff check $(SOURCES)
	uv run ruff format --check $(SOURCES)
	uv run mypy src/ --strict

serve: install  ## Run the service as in production (reads ./.env, ./.mill-data)
	$(BIN)/robotsix-mill serve

dev: install  ## Hot-reload dev server via uvicorn
	$(BIN)/uvicorn --factory robotsix_mill.runtime.api:create_app \
		--reload --reload-dir src --host 127.0.0.1 --port 8077

docker:  ## Build and run the container via docker compose
	docker compose up -d --build

docs-serve: install  ## Live-preview docs at http://127.0.0.1:8000
	uv sync --frozen --group docs
	$(BIN)/mkdocs serve

docs-build: install  ## Build static docs site into site/
	uv sync --frozen --group docs
	$(BIN)/mkdocs build

docs-link-check: install  ## Check docs for broken links (requires lychee)
	uv sync --frozen --group docs
	$(BIN)/mkdocs build
	lychee --config lychee.toml --no-progress docs/

clean:  ## Remove venv, data dirs, and cache files
	rm -rf $(VENV) .mill-data .pytest_cache
	find . -name __pycache__ -type d -exec rm -rf {} +

completions: install  ## Generate shell completion scripts
	$(BIN)/python scripts/gen_completions.py

# ── Alembic migrations ──────────────────────────────────────────────
# ``make migrate`` runs ``alembic upgrade head`` against the default
# mill.db at ``.data/<default-board>/mill.db``.  For per-board DBs,
# use ``scripts/migrate.sh <board_id>`` or call alembic directly with
# the appropriate ``--sqlalchemy.url``.
#
# For the initial Alembic adoption: if you are upgrading from a
# pre-Alembic database (hand-rolled additive migrations), run
# ``make migrate`` — the first run will stamp the existing schema as
# ``head``.  Subsequent runs apply any new migrations.

migrate: install  ## Run Alembic migrations (upgrade head)
	uv run alembic upgrade head

# Create a new autogenerated migration after changing models.
# Usage: ``make migration msg="add foo column to bar"``
migration: install  ## Create new Alembic migration (usage: make migration msg="...")
	uv run alembic revision --autogenerate -m "$(msg)"

# Stamp an existing database as ``head`` without running migrations.
# Useful for bringing a pre-Alembic DB under Alembic tracking.
migrate-stamp: install  ## Stamp existing DB as head without running migrations
	uv run alembic stamp head

check-migrations: install  ## Check for model/migration drift (CI gate)
	uv run alembic --sqlalchemy.url="sqlite:////tmp/drift-check.db" upgrade head
	uv run alembic --sqlalchemy.url="sqlite:////tmp/drift-check.db" check

