"""initial

Revision ID: a6024a92b969
Revises:
Create Date: 2026-07-04 00:04:26.061894

---
Auto-generated by Alembic.

**IMPORTANT** — the ``import sqlmodel`` below is required.  Without it
autogenerated revisions that reference SQLModel column types (e.g.
``AutoString``) will raise ``NameError`` at migration time.  This is
documented at:
https://stackoverflow.com/questions/68932099/how-to-get-alembic-to-recognise-sqlmodel-database-model
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 — required for AutoString etc.


# revision identifiers, used by Alembic.
revision: str = "a6024a92b969"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("board_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("memory", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_memory_board_id"), ["board_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_memory_name"), ["name"], unique=False)

    op.create_table(
        "ticket",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "DRAFT",
                "HUMAN_ISSUE_APPROVAL",
                "READY",
                "DOCUMENTING",
                "CODE_REVIEW",
                "DELIVERABLE",
                "HUMAN_MR_APPROVAL",
                "IMPLEMENT_COMPLETE",
                "WAITING_AUTO_MERGE",
                "MAINTENANCE",
                "REBASING",
                "FIXING_CI",
                "ADDRESSING_REVIEW",
                "DONE",
                "CLOSED",
                "ERRORED",
                "BLOCKED",
                "ASKED",
                "ANSWERED",
                "AWAITING_USER_REPLY",
                "EPIC_OPEN",
                "EPIC_CLOSED",
                name="state",
            ),
            nullable=False,
        ),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("workspace_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("branch", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("parent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("blocked_from", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("paused_from", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("origin_session", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("pre_redraft_cost_usd", sa.Float(), nullable=False),
        sa.Column("review_rounds", sa.Integer(), nullable=False),
        sa.Column("implement_cycles", sa.Integer(), nullable=False),
        sa.Column("refine_passes", sa.Integer(), nullable=False),
        sa.Column(
            "refine_output_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("retry_attempt", sa.Integer(), nullable=False),
        sa.Column(
            "last_transient_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("next_retry_at", sa.DateTime(), nullable=True),
        sa.Column("depends_on", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("unblocks", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("labels", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("board_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("priority", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["ticket.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ticket", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ticket_board_id"), ["board_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ticket_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ticket_priority"), ["priority"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_ticket_state"), ["state"], unique=False)

    op.create_table(
        "comment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticket_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("author", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["comment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["ticket.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_comment_ticket_id"), ["ticket_id"], unique=False
        )

    op.create_table(
        "ticketevent",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticket_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "DRAFT",
                "HUMAN_ISSUE_APPROVAL",
                "READY",
                "DOCUMENTING",
                "CODE_REVIEW",
                "DELIVERABLE",
                "HUMAN_MR_APPROVAL",
                "IMPLEMENT_COMPLETE",
                "WAITING_AUTO_MERGE",
                "MAINTENANCE",
                "REBASING",
                "FIXING_CI",
                "ADDRESSING_REVIEW",
                "DONE",
                "CLOSED",
                "ERRORED",
                "BLOCKED",
                "ASKED",
                "ANSWERED",
                "AWAITING_USER_REPLY",
                "EPIC_OPEN",
                "EPIC_CLOSED",
                name="state",
            ),
            nullable=False,
        ),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("at", sa.DateTime(), nullable=True),
        sa.Column("prev_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["ticket.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ticketevent", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ticketevent_ticket_id"), ["ticket_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ticketevent", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ticketevent_ticket_id"))

    op.drop_table("ticketevent")
    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_comment_ticket_id"))

    op.drop_table("comment")
    with op.batch_alter_table("ticket", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ticket_state"))
        batch_op.drop_index(batch_op.f("ix_ticket_priority"))
        batch_op.drop_index(batch_op.f("ix_ticket_created_at"))
        batch_op.drop_index(batch_op.f("ix_ticket_board_id"))

    op.drop_table("ticket")
    with op.batch_alter_table("memory", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memory_name"))
        batch_op.drop_index(batch_op.f("ix_memory_board_id"))

    op.drop_table("memory")
    # ### end Alembic commands ###
