"""Cross-trace analyser sub-agent.

The retrospect agent's deep-analysis mode invokes this tool after all
per-trace inspections complete.  It examines the per-trace text
summaries together and surfaces patterns that are invisible when
looking at a single trace in isolation — redundant exploration across
stages, information loss between agents, retry cascades, and context
waste.

``run_cross_trace_analyzer`` is the single mockable seam — tests
monkeypatch it to inject synthetic results without a real LLM or
Langfuse.
"""

from __future__ import annotations

import logging
from typing import Literal

from pydantic import BaseModel, Field

from ..config import Settings, get_secrets
from .prompt_blocks import section

log = logging.getLogger("robotsix_mill.cross_trace_analyzer")

_SYSTEM_PROMPT = """\
You are a cross-trace analyser for an autonomous ticket pipeline.
You are given per-trace text summaries from a single ticket session.
You reason from the summaries alone — you have no direct repository access.

Each summary was generated by a per-trace inspector that already
identified tool errors, agent limitations, and optimisation
opportunities **within** that trace.  Your job is to find patterns
that only emerge when you compare traces **across stages**.

Five categories of cross-trace finding:

1. **redundant_exploration** — one agent re-investigates files or
   patterns a prior agent already explored. The canonical case:
   a review agent spending tokens re-exploring files the implement
   agent already read. The fix is typically a handoff summary from
   one stage to the next.

2. **information_loss** — useful discoveries from one stage (tricky
   edge cases, known-broken patterns, gotchas) not propagated to the
   next. The next stage repeats the same discovery work or, worse,
   misses the insight entirely.

3. **retry_cascade** — a failure in one stage (e.g. a flaky test
   gate) causes retries that amplify through later stages. Each
   trace reports retries, but the root cause is only visible by
   comparing them.

4. **context_waste** — multiple agents independently load the same
   large files or run identical expensive tool calls that could be
   cached or shared.

5. **stage_inefficiency** — the stage sequence or assignment could be
   optimised (e.g. two stages each run full-repo exploration when
   the output of one could feed the other).

## How to produce a useful finding

For each finding, output four fields:

- ``category``: one of the five categories above.
- ``symptom``: WHAT is happening, grounded in the per-trace summaries.
  Reference stage names, tool counts, token totals. One sentence.
- ``root_cause``: WHY it's happening. Use your knowledge of the
  pipeline stage structure (implement → test → review → retrospect)
  and the tools available to each agent.
- ``proposed_solution``: a CONCRETE fix. Name files or patterns.
  E.g. "add a handoff summary from implement to review in
  ``stages/review.py``", "cache exploration results in
  ``agents/explore.py`` and serve them across stages".
- ``confidence``: "high" if the pattern is clear from the summaries
  and the pipeline structure confirms the cause; "medium" if you're
  confident about the symptom but less certain of the root cause;
  "low" if it's a guess worth investigating.

## Output discipline

- One finding per ROOT cross-trace issue. Don't split one pattern
  (e.g. implement→review exploration overlap) into three findings.
- An empty findings list is fine when no cross-trace patterns exist.
- Never invent issues. If you cannot ground a proposed solution in
  the summaries, drop the finding or use confidence="low".
- You do NOT have tool access — reason from the summaries alone.
"""

CrossTraceCategory = Literal[
    "redundant_exploration",
    "information_loss",
    "retry_cascade",
    "context_waste",
    "stage_inefficiency",
]
CrossTraceConfidence = Literal["high", "medium", "low"]


class CrossTraceFinding(BaseModel):
    """One actionable cross-trace finding."""

    category: CrossTraceCategory
    symptom: str
    root_cause: str
    proposed_solution: str
    confidence: CrossTraceConfidence = "medium"


class CrossTraceResult(BaseModel):
    findings: list[CrossTraceFinding] = Field(default_factory=list)
    error: str = ""


def run_cross_trace_analyzer(
    *,
    settings: Settings,
    per_trace_summaries: str,
) -> CrossTraceResult:
    """Analyse per-trace summaries for cross-cutting patterns.

    Tool-less — reasons from the text summaries alone. Uses
    ``settings.trace_inspector_model`` (same cheap model as per-trace
    inspection).  ``request_limit=3`` keeps it bounded.

    On error, the result's ``error`` field is populated rather than
    raising — callers degrade gracefully.
    """
    if not get_secrets().openrouter_api_key:
        return CrossTraceResult(error="OPENROUTER_API_KEY is not set")

    from pydantic_ai import Agent, PromptedOutput
    from pydantic_ai.providers.openrouter import OpenRouterProvider
    from pydantic_ai.usage import UsageLimits

    from .base import _close_async_client, timeout_http_client
    from .openrouter_cost import CostInstrumentedOpenRouterModel

    client = timeout_http_client(settings)
    model = CostInstrumentedOpenRouterModel(
        settings.trace_inspector_model,
        provider=OpenRouterProvider(
            api_key=get_secrets().openrouter_api_key,
            http_client=client,
        ),
    )
    agent = Agent(
        model=model,
        system_prompt=_SYSTEM_PROMPT,
        output_type=PromptedOutput(CrossTraceResult),
        tools=[],
    )
    limits = UsageLimits(request_limit=3)
    prompt = (
        "Analyse the following per-trace summaries from a single ticket "
        + "session for cross-trace patterns — redundant exploration, "
        + "information loss, retry cascades, context waste, and stage "
        + "inefficiencies. For each finding, propose a CONCRETE solution.\n\n"
        + section("per-trace-summaries", per_trace_summaries)
    )
    try:
        from .retry import run_agent

        result = run_agent(
            agent,
            lambda h: h.run_sync(prompt, usage_limits=limits),
            settings=settings,
            what="cross_trace_analyzer",
        )
    except Exception as e:  # noqa: BLE001 — degrade, never break the caller
        log.warning("cross-trace analyzer failed: %s", e)
        msg = str(e)
        if "maximum context length" in msg.lower():
            return CrossTraceResult(
                error=f"per-trace summaries too large for model context: {msg[:300]}"
            )
        return CrossTraceResult(error=msg[:500])
    finally:
        _close_async_client(client)
    return result.output


def make_cross_trace_analyze_tool(settings: Settings):
    """Build the ``cross_trace_analyze`` tool exposed to the retrospect
    agent in deep-analysis mode.  It delegates to
    ``run_cross_trace_analyzer`` and returns a formatted Markdown text
    summary — or a degradation message on failure."""

    def cross_trace_analyze(per_trace_summaries: str) -> str:
        """Analyse per-trace summaries for cross-cutting patterns.
        Call this ONCE after all trace_inspect calls complete.  Pass
        ALL per-trace summaries together, separated by stage names.
        Returns a Markdown summary of cross-trace findings."""
        result = run_cross_trace_analyzer(
            settings=settings,
            per_trace_summaries=per_trace_summaries,
        )

        parts: list[str] = ["## cross-trace analysis"]
        if result.error:
            parts.append(f"\n_analyzer error: {result.error[:200]}_")
            return "\n".join(parts)

        by_cat: dict[str, list[CrossTraceFinding]] = {
            "redundant_exploration": [],
            "information_loss": [],
            "retry_cascade": [],
            "context_waste": [],
            "stage_inefficiency": [],
        }
        for f in result.findings:
            by_cat[f.category].append(f)

        section_titles = {
            "redundant_exploration": "Redundant Exploration",
            "information_loss": "Information Loss",
            "retry_cascade": "Retry Cascades",
            "context_waste": "Context Waste",
            "stage_inefficiency": "Stage Inefficiencies",
        }
        for cat, title in section_titles.items():
            items = by_cat.get(cat, [])
            if not items:
                continue
            parts.append(f"\n### {title}")
            for f in items:
                line = f"- {f.symptom}"
                if f.proposed_solution:
                    line += f"  _(fix: {f.proposed_solution[:200]})_"
                parts.append(line)

        if not result.findings:
            parts.append("\n(no cross-trace patterns found)")
        return "\n".join(parts)

    return cross_trace_analyze
