"""Settings field mixin: review gate (implement → deliver).

Field-only pydantic mixin extracted from the monolithic ``Settings``
model to keep ``settings.py`` under 800 lines. Assembled into the final
``Settings`` class in ``config/settings.py``.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class _ReviewGateSettings(BaseModel):
    # --- dual-model review gate (implement → deliver) ---
    # When true, the implement stage transitions to code_review instead of
    # deliverable. A dedicated review agent audits the diff blind before the
    # deliver stage pushes + opens the PR. Default False (opt-in).
    review_enabled: bool = Field(
        description="When true, implement transitions to code_review before deliver.",
        default=False,
    )
    # When true (and review is enabled + the review agent marks the
    # change as auto-merge-eligible), the merge stage will attempt to
    # merge its own green PR via the forge API without waiting for a
    # human. Default True (opt-out).
    auto_merge_enabled: bool = Field(
        description="When true, the merge stage auto-merges green PRs via the forge API.",
        default=True,
    )
    # When True (default), the single-repo auto-merge decision detects
    # pre-existing main-branch CI debt: if every workflow failing on the
    # PR head is ALSO failing on the merge target, the failure was not
    # introduced by this PR and the ticket is routed to BLOCKED instead
    # of cycling rebase/ci-fix retries. Safe-by-default — it only ever
    # fires when main is demonstrably red on the same workflow(s); the
    # flag exists so an operator can disable it.
    auto_merge_main_debt_detection_enabled: bool = Field(
        description="When true, detect pre-existing main-branch CI debt to avoid rebase/ci-fix retry loops.",
        default=True,
        json_schema_extra={"advanced": True},
    )
    # When True (default False), all auto-merge is suppressed globally
    # regardless of per-repo toggles.  Emergency kill-switch — the
    # operator flips this to halt all autonomous merges immediately.
    auto_merge_kill_switch: bool = Field(
        description="When true, suppress ALL auto-merge globally (emergency kill-switch).",
        default=False,
    )
    # Glob patterns for files/directories that block auto-merge when
    # touched by a PR.  A PR that touches ANY of these paths will NEVER
    # be auto-merged, regardless of the per-repo toggle — it must route
    # to human approval.  The match is against the full repo-relative
    # path (e.g. ".github/workflows/ci.yml").
    auto_merge_sensitive_globs: list[str] = Field(
        default_factory=lambda: [
            ".github/workflows/**",
            "**/secrets/**",
            "**/*.secret*",
            ".env*",
        ],
        description="Glob patterns for files that always block auto-merge when touched.",
    )
    # Paths the post-rebase drop guard must not treat as evidence that the
    # rebase agent discarded the PR's work.  Matched as exact paths or as
    # directory prefixes against the repo-relative path.
    #
    # These are registry and boilerplate files: mechanical bookkeeping that
    # every ticket touches at the same spot, and that CI re-derives on merge
    # (auto-fix commits for changelog and module registration are routine).
    # Their content is a function of the whole repo rather than of one branch,
    # so a rebase legitimately reconciles them to something that is neither
    # the branch's version nor the target's previous one.  The blob-equality
    # excuse below cannot clear that case — it only excuses a target that
    # already carries byte-for-byte what the branch was delivering — so
    # without this list a healthy reconciliation is reported as a silent drop
    # and the ticket dead-ends.  Observed live on 2026-08-07: six auto-mail
    # tickets blocked in twelve minutes, all on ``docs/modules.yaml``.
    #
    # Keep genuine implement-stage paths OUT of this list. Anything here is
    # invisible to the guard, which is precisely what makes it safe only for
    # files whose loss another gate would catch.
    rebase_drop_exempt_paths: list[str] = Field(
        default_factory=lambda: [
            "CHANGELOG.md",
            "changelog.d/",
            "changelog/",
            "docs/modules.yaml",
            "site/modules.yaml",
            # detect-secrets' baseline: regenerated from a whole-repo scan,
            # so like the registries above its content is a function of the
            # tree rather than of one branch.
            ".secrets.baseline",
            # uv's resolved lockfile: regenerated by ``uv lock`` from the
            # whole dependency graph, so a dependency a sibling PR already
            # landed collapses this branch's lock delta to nothing.
            "uv.lock",
        ],
        description=(
            "Repo-relative paths/prefixes the post-rebase drop guard ignores "
            "(registry and boilerplate files CI re-derives)."
        ),
    )
    # Repo IDs permanently excluded from auto-merge (cannot be opted in).
    # Default includes the infra repo; an operator can add more.
    auto_merge_infra_denylist: list[str] = Field(
        default_factory=lambda: ["robotsix-central-deploy"],
        description="Repo IDs permanently excluded from auto-merge.",
    )
    # When True, the board's ticket detail drawer renders description.md
    # below the comments with a collapsible "Hide" toggle (the frontend
    # reads ``gatesCache.comments_after_body``). Default False (opt-in).
    comments_after_body: bool = Field(
        description="When true, the board detail drawer renders description.md below comments.",
        default=False,
    )
    # When True (and a human reviewer requests changes on the PR),
    # the merge stage will invoke the review-revision agent to
    # implement the requested changes automatically. Default False
    # (opt-in — this is a powerful autonomous capability).
    review_feedback_enabled: bool = Field(
        description="When true, the review-revision agent auto-implements requested PR changes.",
        default=False,
    )
    # When True (default), a cheap triage LLM call runs before the full
    # refine agent.  Drafts that are already precise, single-scoped, and
    # implementation-ready skip the full refine — saving cost & latency.
    # Set False to force full refine for all tickets without a deploy.
    refine_triage_enabled: bool = Field(
        description="When true, a cheap triage LLM call runs before full refine for implementation-ready drafts.",
        default=True,
    )
    # When a ticket draft contains more than this many lines of code
    # inside fenced code blocks (triple backticks), the draft is
    # treated as a prescriptive spec — the ticket skips the refine
    # LLM entirely and routes directly to implement.  Set to 0 to
    # disable the deterministic shortcut.  Default 50.
    refine_prescriptive_spec_code_lines_threshold: int = Field(
        description="Drafts with more than this many fenced code lines skip refine entirely.",
        default=50,
        json_schema_extra={"advanced": True},
    )
    # When True (default), the refine stage detects specs whose
    # implementation section already contains complete file-path +
    # fenced-code-block changes.  For these "implementation-ready"
    # specs, it runs a cheap deterministic validation pass (file
    # existence, YAML/Python syntax, forbidden patterns) and bypasses
    # the expensive LLM refine agent entirely — saving cost and latency.
    # When the validation finds a problem, it falls back to the normal
    # LLM path.  Set False to always run the full refine agent.
    refine_skip_llm_on_impl_ready_spec: bool = Field(
        description="When true, implementation-ready specs skip the expensive LLM refine agent.",
        default=True,
        json_schema_extra={"advanced": True},
    )
    # When True (default), a pre-Opus guard checks whether the reviewer's
    # feedback on a sendback ticket already agrees with the draft's
    # no-change-needed conclusion.  When the reviewer confirms, the
    # pipeline short-circuits to DONE, skipping the expensive Opus refine
    # agent (~$0.28).  Requires ``refine_triage_enabled=True``.
    reviewer_agreement_gate_enabled: bool = Field(
        description="When true, reviewer agreement with a no-change-needed conclusion short-circuits to DONE.",
        default=True,
        json_schema_extra={"advanced": True},
    )
    # When True (default), the cheap advisory-dedup-verification gate runs
    # after the inflight-advisory phase and before the expensive refine
    # agent. It resolves any carried ``Possible duplicate of <id>`` advisory
    # with a single cheapest-tier ``run_dedup_check`` against only the named
    # candidate. On a confirmed valid duplicate, the ticket is short-circuited
    # to DONE; otherwise the advisory is cleared and refine proceeds.
    # Set False to disable the gate entirely (advisories are left intact and
    # the full refine agent runs).
    refine_advisory_dedup_enabled: bool = Field(
        description="When true, a cheap advisory-dedup-verification gate runs after inflight-advisory phase.",
        default=True,
        json_schema_extra={"advanced": True},
    )
    # When True, a deterministic pre-refine gate verifies that file paths
    # and line ranges cited in the ticket draft still exist on the
    # working branch's HEAD.  When the cited evidence has gone stale
    # (upstream rewrite, sibling commit, or hallucinated finding) the
    # ticket is short-circuited to DONE before the expensive refine
    # agent runs.  Default False (opt-in).
    freshness_gate_enabled: bool = Field(
        description="When true, a pre-refine gate verifies cited file paths and line ranges still exist on HEAD.",
        default=False,
    )
    # When True, an LLM-based pre-refine gate re-evaluates whether a
    # spawned follow-up/corrective draft's cited gap (e.g. "add doc
    # section X", "remove dependency Y") still exists on HEAD.  When the
    # gap was already resolved in place by a parallel/parent ticket the
    # ticket is short-circuited to DONE before the expensive refine
    # agent runs.  Default False (opt-in — auto-closing tickets is
    # risky).
    obsolescence_gate_enabled: bool = Field(
        description="When true, an LLM pre-refine gate re-evaluates whether a cited gap still exists on HEAD.",
        default=False,
    )
    # When True (default), a single-LLM-call pre-refine gate checks the
    # draft's GOAL against robotsix-standards for repos that follow the
    # fleet conventions (RepoConfig.follows_robotsix_standards()).  A
    # draft whose objective clearly requires something a standard
    # explicitly prohibits (e.g. "publish to npm" vs the
    # distribution-packaging no-registry rule) is short-circuited to
    # DONE with the citation before any refine budget is spent.  The
    # gate is conservative (≥90% confidence, prohibition-only) and
    # never fires on user-authored drafts or non-fleet repos.
    standards_gate_enabled: bool = Field(
        description="When true, an LLM pre-refine gate discards drafts whose goal violates an explicit robotsix-standards prohibition (fleet repos only).",
        default=True,
    )
    # When True (default), a deterministic pre-refine gate detects
    # drafts that reference mill-specific source paths
    # When True, a deterministic pre-implement gate verifies that
    # external symbol/import prerequisites the spec declares in a
    # ``## Prerequisites`` / ````prereq```` block are satisfiable in the
    # cloned repo's environment.  When a declared prerequisite is not yet
    # importable (e.g. an unmerged external port) the ticket is
    # short-circuited to BLOCKED before the expensive implement agent
    # runs — the work is still required once the upstream symbol lands.
    # Default True: this is a no-op for the common case (a spec that
    # declares no ``## Prerequisites`` block — ``run_prerequisite_check``
    # returns early with empty ``unmet``) and degrades gracefully (any
    # checker error → proceed, never blocks); it only ever blocks on an
    # explicitly declared, verifiably unmet directive.
    prerequisite_gate_enabled: bool = Field(
        description="When true, a pre-implement gate verifies declared import prerequisites are satisfiable.",
        default=True,
    )
    # When True, the refine stage runs a post-refinement review pass that
    # strips verbose exploratory narrative from the spec, producing a
    # concise version while saving the verbose original as an artifact.
    # Defaults to True — the $0.0003 spec-review pass strips verbose
    # narrative, saving significant token cost on downstream agents.
    spec_review_enabled: bool = Field(
        description="When true, a post-refinement review pass strips verbose narrative from the spec.",
        default=True,
    )
    # When True (default), a cheap scope-triage LLM call inspects
    # out-of-scope file changes before blocking the ticket. The agent
    # decides EXPAND (legitimate), REJECT (scope creep), or ESCALATE
    # (uncertain). Set False to restore immediate BLOCKED behaviour.
    scope_triage_enabled: bool = Field(
        description="When true, a cheap scope-triage LLM inspects out-of-scope file changes before blocking.",
        default=True,
    )
    # When True, the deliver stage generates a structured PR body
    # (Summary / Changes / Test Plan) from the implementation diff
    # via a cheap one-shot LLM call instead of pasting the raw spec.
    pr_summary_enabled: bool = Field(
        description="When true, the deliver stage generates a structured PR body from the diff.",
        default=False,
    )
    # When True, Forge.create_repo() is permitted to create repositories
    # via the forge API. Default False (opt-in) — the operator must
    # explicitly enable this and ensure the GitHub App installation has
    # the necessary repository-creation scope.
    enable_repo_creation: bool = Field(
        description="When true, Forge.create_repo() is permitted to create repositories via the forge API.",
        default=False,
    )
    # Default visibility for newly created repositories.
    # "public" — repos are public unless the caller specifies private=True.
    # "private" — repos are private unless the caller specifies private=False.
    repo_visibility_default: Literal["public", "private"] = Field(
        default="public",
        description="Default visibility for newly created repositories: public or private.",
    )
    # When True, the merge stage deletes the per-ticket head branch on the
    # forge after a ticket merges to DONE. Default True — cleans up
    # mill/<id> branches automatically; set False to keep them.
    delete_branch_on_merge: bool = Field(
        description="When true, the merge stage deletes the per-ticket head branch on the forge after merge.",
        default=True,
    )
    # -- periodic stale-branch cleanup --
    # When True, the worker runs a periodic pass that lists remote branches
    # and deletes old, unprotected, no-open-PR branches (per prefix/age guards).
    # Default False — destructive, opt-in.
    stale_branch_cleanup_periodic: bool = Field(
        description="When true, run periodic stale-branch cleanup passes.",
        default=False,
    )
    # Seconds between automatic stale-branch cleanup passes. Only used when
    # MILL_STALE_BRANCH_CLEANUP_PERIODIC=true. Enforced minimum 3600s (1h)
    # in the worker to avoid hammering the forge API.
    stale_branch_cleanup_interval_seconds: int = Field(
        description="Seconds between automatic stale-branch cleanup passes.",
        default=86400,
        json_schema_extra={"advanced": True},
    )
    # A branch is eligible for cleanup only if its last commit is older than
    # this many days. Default 30 days.
    stale_branch_max_age_days: int = Field(
        description="Branch is eligible for cleanup only if its last commit is older than this many days.",
        default=30,
        json_schema_extra={"advanced": True},
    )
    # When True, only delete branches whose name starts with ``branch_prefix``
    # (the "old mill" branches). When False, also reap any other stale branch
    # ("stale dev").
    stale_branch_cleanup_prefix_only: bool = Field(
        description="When true, only delete branches matching branch_prefix.",
        default=True,
        json_schema_extra={"advanced": True},
    )
    # Maximum number of CODE_REVIEW → READY → DOCUMENTING → CODE_REVIEW
    # round-trips before escalating to DELIVERABLE for human merge approval.
    # A value ≤ 0 means escalate on the first REQUEST_CHANGES (the loop is
    # effectively disabled). Default 3.
    review_max_rounds: int = Field(
        description="Maximum CODE_REVIEW to READY to DOCUMENTING to CODE_REVIEW round-trips before escalation.",
        default=3,
        ge=0,
        json_schema_extra={"advanced": True},
    )

    # Backstop ceiling on total implement passes per ticket (across all
    # review rounds, ticket lifetime).  Exceeding this limit escalates the
    # ticket to BLOCKED for human inspection.  Set higher than the product
    # of ``review_max_rounds`` × ``max_fix_iterations`` to ensure it only
    # fires as a genuine runaway backstop, not as normal operation.  Default
    # 10 is generous enough for 3 review rounds with ~3 fix iterations each.
    # Set to 0 to disable.
    max_implement_review_cycles: int = Field(
        description="Ceiling on total implement passes per ticket across all review rounds. 0 disables.",
        default=10,
        ge=0,
        json_schema_extra={"advanced": True},
    )
    # Maximum number of times the implement stage may be entered (spawned)
    # for a single ticket — counted across all review rounds and resumptions.
    # Unlike ``max_implement_review_cycles`` (which only counts successful
    # passes that reach CODE_REVIEW), this gate counts EVERY invocation
    # including BLOCKED→READY resumptions and no-change passes.  Catching
    # the redundant $0.00 + extra paid attempt pattern where a ticket
    # loops through implement 3+ times with empty results.  Default 3 is
    # tight enough to prevent the observed pattern while leaving room for
    # one successful run.  Set to 0 to disable.
    implement_max_spawns_per_ticket: int = Field(
        description="Maximum times the implement stage may be entered per ticket. 0 disables.",
        default=3,
        ge=0,
        json_schema_extra={"advanced": True},
    )
    # Number of consecutive no-progress BLOCKED implement cycles after
    # which the stall guard fires with an actionable diagnostic instead
    # of silently consuming another spawn round.  A cycle is "no-progress"
    # when the implement agent's summary is byte-identical to the previous
    # blocked attempt.  Default 2 means: after two consecutive cycles with
    # the same summary (and no file changes), the third attempt is blocked
    # BEFORE opening a trace.  Set to 0 to disable.
    implement_stall_threshold: int = Field(
        description="Consecutive no-progress BLOCKED cycles before stall guard fires. 0 disables.",
        default=2,
        ge=0,
        json_schema_extra={"advanced": True},
    )
    # Consecutive zero-diff implement passes before the early-abort guard
    # pauses the ticket via ask_user instead of consuming further spawn
    # attempts.  A pass that produces at least one file edit resets the
    # counter.  Default 2 catches the no-op thrash pattern without
    # penalising legitimate multi-pass fixes.  0 disables the guard.
    # Configured via ``implement_zero_diff_abort_threshold`` in the
    # YAML config.
    implement_zero_diff_abort_threshold: int = Field(
        description="Consecutive zero-diff implement passes before pausing with ask_user. 0 disables.",
        default=2,
        ge=0,
        json_schema_extra={"advanced": True},
    )
    # How many model requests the review agent may make in one run
    # (counts each tool call + each reasoning step + the final verdict).
    # 20 (original) then 40 each routinely BLOCKED medium PRs with
    # "review agent error — resumable" mid-review. 40 was *still* too low:
    # test-heavy / multi-file diffs make the reviewer read_file the
    # source-under-test plus related modules to verify claims (the
    # preloaded reference_files cover only the modified files), and 40 was
    # exhausted on three tickets in one day (f0eb, 741f, 2e8d — each a
    # test-gap or multi-file change). Unlike refine, review has no explore
    # sub-agent to delegate breadth reads to, so the cap itself is the
    # lever; match refine's 80 (same reasoning: per-run cost is negligible
    # ~$0.03-0.09 and the per-ticket spend cap is the real backstop). See
    # ticket bc6d.
    review_request_limit: int = Field(
        description="Per-call request cap for the review agent.",
        default=80,
        json_schema_extra={"advanced": True},
    )
    # Maximum characters of the re-review prior-context block (prior
    # review comments + the implement rebuttal) fed to the review agent.
    # Each component is tail-kept (most-recent content survives) so multi-
    # round reviews don't re-pay for the entire accumulated history. 0
    # disables the cap.
    review_prior_context_max_chars: int = Field(
        description="Maximum characters of prior review context fed to the review agent. 0 disables.",
        default=8000,
        ge=0,
        json_schema_extra={"advanced": True},
    )
    # Maximum characters of the combined git diff injected into the review
    # prompt. The raw ``git diff origin/<target>...HEAD`` can balloon to
    # megabytes (divergent base, generated/lockfile churn, branch history)
    # regardless of how few lines the intended change touches, overflowing
    # even a 1M-token model context. Middle-truncated (head+tail) so both
    # early and late files get representation. ~200K chars ≈ 50K tokens
    # leaves ample room for spec + prior context + preseed + tools + the
    # output reservation. 0 disables the cap.
    review_diff_max_chars: int = Field(
        description="Maximum characters of the combined git diff injected into the review prompt. 0 disables.",
        default=200_000,
        ge=0,
        json_schema_extra={"advanced": True},
    )
    # When the combined diff exceeds ``review_diff_max_chars``, thin each
    # hunk's context runs down to this many lines per side BEFORE the
    # head+tail hard cap. ``git diff`` already emits 3 context lines, so a
    # value of 1 removes the extra context lines that dominate large,
    # scattered diffs while the preseed excerpts (below) still give the
    # reviewer surrounding code. 0 keeps the full 3-line context and relies
    # on head+tail truncation alone.
    review_diff_context_lines: int = Field(
        description="Max surrounding context lines kept per hunk when the review diff exceeds review_diff_max_chars. 0 disables hunk thinning.",
        default=1,
        ge=0,
        json_schema_extra={"advanced": True},
    )
    # Lines of file context around each changed region preloaded in the
    # review preseed. Replaces the old whole-file preload: for a modified
    # file we now send only the changed lines plus this much surrounding
    # context, and the reviewer calls read_file(path, offset, limit) for
    # anything else it needs. 0 preloads only the changed lines themselves.
    review_preseed_context_lines: int = Field(
        description="Lines of file context around each changed region preloaded in the review preseed. 0 preloads only changed lines.",
        default=40,
        ge=0,
        json_schema_extra={"advanced": True},
    )
    # Output token budget for the review agent retry when the primary
    # attempt exhausts its max_tokens before generating a response
    # (the reasoning model burns output tokens on internal reasoning).
    # This is the *retry* budget; the primary attempt uses the YAML
    # max_tokens. Set higher than the YAML max_tokens. 0 disables the
    # output-exhaustion retry (falls straight to NEEDS_DISCUSSION).
    review_output_token_budget: int = Field(
        description="Output token budget for the review agent retry on max_tokens exhaustion. 0 disables.",
        default=65536,
        ge=0,
        json_schema_extra={"advanced": True},
    )
    # Maximum number of out-of-scope TEXT files fed into the scope-triage
    # prompt. When an implement pass leaves MORE than this many out-of-scope
    # text files (after binary-artifact auto-cleanup), treat it as a build-
    # artifact flood: skip the scope-triage LLM entirely (its prompt would
    # balloon to thousands of diff summaries) and block deterministically for
    # human review. Default 50 leaves normal PRs untouched. 0 disables.
    # Absolute ceiling on out-of-scope text files, counted WITHOUT the
    # newly-added filter that ``scope_triage_max_files`` applies. That filter
    # exists so a wide refactor is not mistaken for an artifact flood, but the
    # original cap also protected the scope-triage prompt from overflowing,
    # and that protection still has to live somewhere. Set well above any
    # plausible hand-written change: a refactor touching 500+ files is worth
    # stopping on its own merits. 0 disables the ceiling.
    scope_triage_hard_max_files: int = Field(
        default=500,
        ge=0,
        description=(
            "Absolute cap on out-of-scope text files before the scope-triage "
            "LLM is skipped, regardless of whether they are newly added."
        ),
        json_schema_extra={"advanced": True},
    )
    scope_triage_max_files: int = Field(
        description="Maximum out-of-scope text files fed to the scope-triage prompt. 0 disables.",
        default=50,
        ge=0,
        json_schema_extra={"advanced": True},
    )
    # Per-call cap for pre-refine triage agent (main call + tool calls).
    triage_request_limit: int = Field(
        description="Per-call request cap for the pre-refine triage agent.",
        default=8,
        json_schema_extra={"advanced": True},
    )
