#!/usr/bin/env python3
"""Render a security-hardening wrapper Dockerfile.

The reusable Docker publish/scan workflows build a component's image from
its own ``Dockerfile`` (``FROM debian:13.x`` and friends).  When the base
layer ships an unpatched package (e.g. ``perl-base 5.40.1-6`` before the
``+deb13u1`` security fix), the built image fails the Trivy CRITICAL gate.

Rather than every fleet component editing its own Dockerfile, the shared
workflow injects an ``apt-get`` security-upgrade layer on top of the freshly
built image.  This module renders that wrapper Dockerfile:

    FROM <built-image>
    USER root
    RUN <apt-get upgrade, guarded so non-apt images are a no-op>
    USER <original user>          # only when the base ran as non-root

Running the upgrade as ``root`` is required (``apt-get`` needs it); the
original ``USER`` is then restored so runtime behaviour is unchanged.

This lives in ``scripts/`` as an importable module (AGENT.md Rule 6) so the
workflow invokes ``python3 scripts/render_harden_dockerfile.py`` and the unit
tests exercise the exact same logic — the workflow cannot drift from what is
tested.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

# The upgrade step.  Guarded with ``command -v apt-get`` so an image built on
# a non-Debian base (e.g. Alpine) is a harmless no-op rather than a build
# failure.  ``DEBIAN_FRONTEND=noninteractive`` keeps apt from prompting; the
# apt lists are removed afterwards to avoid bloating the final image.
_APT_RUN = (
    "RUN set -eux; \\\n"
    "    if command -v apt-get >/dev/null 2>&1; then \\\n"
    "        export DEBIAN_FRONTEND=noninteractive; \\\n"
    "        apt-get update; \\\n"
    "        apt-get -y --no-install-recommends upgrade; \\\n"
    "        apt-get clean; \\\n"
    "        rm -rf /var/lib/apt/lists/*; \\\n"
    "    fi"
)


def extract_user(config: Any) -> str:
    """Return the ``User`` configured on an image, or ``""`` when root/unset.

    Tolerant of the several JSON shapes the workflow may feed in:

    * ``docker inspect --format '{{json .Config}}'`` -> ``{"User": "app", ...}``
    * ``docker buildx imagetools inspect --format '{{json .Image}}'`` ->
      an OCI image config ``{"config": {"User": "app"}, ...}``
    * a per-platform map ``{"linux/amd64": {"config": {...}}, ...}`` (an
      image index / manifest list).

    Anything unrecognised (``None``, wrong type, missing key) yields ``""`` so
    the caller keeps the image running as root — a safe, build-passing default.
    """
    if not isinstance(config, dict):
        return ""
    # OCI image config: the User lives under a nested "config" object.
    nested = config.get("config")
    if isinstance(nested, dict) and "User" in nested:
        return str(nested.get("User") or "").strip()
    # docker inspect .Config: User at the top level.
    if "User" in config:
        return str(config.get("User") or "").strip()
    # Image index / manifest list keyed by platform. Prefer linux/amd64, then
    # fall back to any platform entry that declares a user.
    ordered_keys = ["linux/amd64", *config.keys()]
    for key in ordered_keys:
        value = config.get(key)
        if isinstance(value, dict):
            user = extract_user(value)
            if user:
                return user
    return ""


def render(base_ref: str, user: str = "", *, apt: bool = True) -> str:
    """Render the hardening Dockerfile as text.

    ``base_ref`` is the fully-qualified reference of the already-built image
    (a registry ``name@sha256:...`` digest or a local tag).  ``user`` is the
    base image's original ``USER``; when it is empty or root the wrapper simply
    stays root (which matches the base).  ``apt=False`` omits the upgrade step
    (used only by tests / dry runs).
    """
    if not base_ref or not base_ref.strip():
        raise ValueError("base_ref must be a non-empty image reference")

    lines = [
        "# Auto-generated by scripts/render_harden_dockerfile.py -- do not edit.",
        "# Injects OS security upgrades on top of the built image so published",
        "# images pick up patched packages (e.g. perl-base >= 5.40.1-6+deb13u1)",
        "# and pass the Trivy CRITICAL gate.",
        f"FROM {base_ref.strip()}",
        "USER root",
    ]
    if apt:
        lines.append(_APT_RUN)

    restore = (user or "").strip()
    if restore and restore not in ("root", "0"):
        lines.append(f"USER {restore}")

    return "\n".join(lines) + "\n"


def _load_config(path: str | None) -> Any:
    if not path:
        return None
    text = Path(path).read_text(encoding="utf-8").strip()
    if not text:
        return None
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        # A malformed / empty inspect output must not break publishing; fall
        # back to running as root (no USER restore line).
        return None


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--base-ref",
        required=True,
        help="Reference of the built image to harden (name@digest or tag).",
    )
    parser.add_argument(
        "--config",
        default=None,
        help="Path to the base image config JSON (docker inspect .Config or "
        "buildx imagetools inspect .Image output). Optional.",
    )
    parser.add_argument(
        "--out",
        default=None,
        help="Path to write the rendered Dockerfile. Defaults to stdout.",
    )
    parser.add_argument(
        "--no-apt",
        action="store_true",
        help="Omit the apt-get upgrade layer (dry run / testing).",
    )
    args = parser.parse_args(argv)

    user = extract_user(_load_config(args.config))
    dockerfile = render(args.base_ref, user, apt=not args.no_apt)

    if args.out:
        Path(args.out).write_text(dockerfile, encoding="utf-8")
    else:
        sys.stdout.write(dockerfile)
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
