name: Deploy Server Release

on:
  push:
    branches: [main]
    paths:
      - "src/robotsix_deploy/**"
      - "Dockerfile.deploy"
      - ".github/workflows/deploy-server-release.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    uses: damien-robotsix/robotsix-github-workflows/.github/workflows/docker-release.yml@5cd8c1facb02299da618979e7a55f1953f9c075a
    with:
      dockerfile: "./Dockerfile.deploy"
