name: Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy:
    permissions:
      contents: write
    uses: ./.github/workflows/python-docs.yml
    with:
      docs-install-args: "--group docs"
      python-version: "3.14"
      uv-version: "0.8.15"
      retries: "4"
