#compdef robotsix-mill

# AUTOMATICALLY GENERATED by `shtab`


_shtab_robotsix_mill_commands() {
  local _commands=(
    "agent-check:"
    "audit:"
    "bc-check:"
    "completeness-check:"
    "config-sync:"
    "copy-paste:"
    "diagnostic:"
    "epic:"
    "forge-parity:"
    "health:"
    "inquire:"
    "langfuse-cleanup:"
    "member-sync:"
    "meta:"
    "module-curator:"
    "repos:"
    "roadmap-sync:"
    "run-health:"
    "serve:"
    "survey:"
    "test-gap:"
    "ticket:"
    "trace-health:"
    "trace-review:"
    "verify:"
  )
  _describe 'robotsix-mill commands' _commands
}

_shtab_robotsix_mill_epic_commands() {
  local _commands=(
    "new:"
  )
  _describe 'robotsix-mill epic commands' _commands
}

_shtab_robotsix_mill_repos_commands() {
  local _commands=(
    "list:"
  )
  _describe 'robotsix-mill repos commands' _commands
}

_shtab_robotsix_mill_ticket_commands() {
  local _commands=(
    "approve:"
    "list:"
    "new:"
    "resume-blocked:"
    "show:"
  )
  _describe 'robotsix-mill ticket commands' _commands
}

_shtab_robotsix_mill_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--print-completion[print shell completion script for the specified shell]:print_completion:(bash zsh tcsh)"
)

# guard to ensure default positional specs are added only once per session
_shtab_robotsix_mill_defaults_added=0

_shtab_robotsix_mill_agent_check_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[output full JSON result (default\: summary)]"
)

# guard to ensure default positional specs are added only once per session
_shtab_robotsix_mill_agent_check_defaults_added=0

_shtab_robotsix_mill_audit_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[output full JSON result (default\: summary)]"
)

# guard to ensure default positional specs are added only once per session
_shtab_robotsix_mill_audit_defaults_added=0

_shtab_robotsix_mill_bc_check_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[output full JSON result (default\: summary)]"
)

# guard to ensure default positional specs are added only once per session
_shtab_robotsix_mill_bc_check_defaults_added=0

_shtab_robotsix_mill_completeness_check_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[output full JSON result (default\: summary)]"
)

# guard to ensure default positional specs are added only once per session
_shtab_robotsix_mill_completeness_check_defaults_added=0

_shtab_robotsix_mill_config_sync_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[output full JSON result (default\: summary)]"
)

# guard to ensure default positional specs are added only once per session
_shtab_robotsix_mill_config_sync_defaults_added=0

_shtab_robotsix_mill_copy_paste_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[output full JSON result (default\: summary)]"
)

# guard to ensure default positional specs are added only once per session
_shtab_robotsix_mill_copy_paste_defaults_added=0

_shtab_robotsix_mill_diagnostic_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[output full JSON result (default\: summary)]"
)

# guard to ensure default positional specs are added only once per session
_shtab_robotsix_mill_diagnostic_defaults_added=0

_shtab_robotsix_mill_epic_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
)

# guard to ensure default positional specs are added only once per session
_shtab_robotsix_mill_epic_defaults_added=0

_shtab_robotsix_mill_epic_new_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--title[]:title:"
  "--description-file[file with the description\; \'-\' reads stdin]:description_file:"
  "--repo-id[repository identifier (required when multiple repos are registered\; optional when only one)]:repo_id:"
)

# guard to ensure default positional specs are added only once per session
_shtab_robotsix_mill_epic_new_defaults_added=0

_shtab_robotsix_mill_forge_parity_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[output full JSON result (default\: summary)]"
)

# guard to ensure default positional specs are added only once per session
_shtab_robotsix_mill_forge_parity_defaults_added=0

_shtab_robotsix_mill_health_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[output full JSON result (default\: summary)]"
)

# guard to ensure default positional specs are added only once per session
_shtab_robotsix_mill_health_defaults_added=0

_shtab_robotsix_mill_inquire_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--title[]:title:"
  "--description-file[file with the question body\; \'-\' reads stdin]:description_file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_robotsix_mill_inquire_defaults_added=0

_shtab_robotsix_mill_langfuse_cleanup_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[output full JSON result (default\: summary)]"
)

# guard to ensure default positional specs are added only once per session
_shtab_robotsix_mill_langfuse_cleanup_defaults_added=0

_shtab_robotsix_mill_member_sync_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[output full JSON result (default\: summary)]"
  "--repo-id[master repo to sync members from (required if multiple repos)]:repo_id:"
)

# guard to ensure default positional specs are added only once per session
_shtab_robotsix_mill_member_sync_defaults_added=0

_shtab_robotsix_mill_meta_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[output full JSON result (default\: summary)]"
)

# guard to ensure default positional specs are added only once per session
_shtab_robotsix_mill_meta_defaults_added=0

_shtab_robotsix_mill_module_curator_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[output full JSON result (default\: summary)]"
)

# guard to ensure default positional specs are added only once per session
_shtab_robotsix_mill_module_curator_defaults_added=0

_shtab_robotsix_mill_repos_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
)

# guard to ensure default positional specs are added only once per session
_shtab_robotsix_mill_repos_defaults_added=0

_shtab_robotsix_mill_repos_list_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
)

# guard to ensure default positional specs are added only once per session
_shtab_robotsix_mill_repos_list_defaults_added=0

_shtab_robotsix_mill_roadmap_sync_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[output raw JSON instead of human-friendly text]"
  "--repo-id[repository to run roadmap-sync for (required if multiple repos)]:repo_id:"
)

# guard to ensure default positional specs are added only once per session
_shtab_robotsix_mill_roadmap_sync_defaults_added=0

_shtab_robotsix_mill_run_health_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[output full JSON result (default\: summary)]"
)

# guard to ensure default positional specs are added only once per session
_shtab_robotsix_mill_run_health_defaults_added=0

_shtab_robotsix_mill_serve_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--repo-id[repository identifier to serve a single repo\; omit to serve all repos from config\/repos.yaml]:repo_id:"
)

# guard to ensure default positional specs are added only once per session
_shtab_robotsix_mill_serve_defaults_added=0

_shtab_robotsix_mill_survey_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[output full JSON result (default\: summary)]"
)

# guard to ensure default positional specs are added only once per session
_shtab_robotsix_mill_survey_defaults_added=0

_shtab_robotsix_mill_test_gap_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[output full JSON result (default\: summary)]"
)

# guard to ensure default positional specs are added only once per session
_shtab_robotsix_mill_test_gap_defaults_added=0

_shtab_robotsix_mill_ticket_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
)

# guard to ensure default positional specs are added only once per session
_shtab_robotsix_mill_ticket_defaults_added=0

_shtab_robotsix_mill_ticket_approve_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  ":id:"
)

# guard to ensure default positional specs are added only once per session
_shtab_robotsix_mill_ticket_approve_defaults_added=0

_shtab_robotsix_mill_ticket_list_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--state[]:state:(draft human_issue_approval ready documenting code_review deliverable human_mr_approval implement_complete waiting_auto_merge rebasing fixing_ci addressing_review done closed errored blocked asked answered awaiting_user_reply epic_open epic_closed)"
  "--repo-id[filter tickets by repository (list all when omitted)]:repo_id:"
)

# guard to ensure default positional specs are added only once per session
_shtab_robotsix_mill_ticket_list_defaults_added=0

_shtab_robotsix_mill_ticket_new_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--title[]:title:"
  "--description-file[file with the body\; \'-\' reads stdin]:description_file:"
  "--repo-id[repository identifier (required when multiple repos are registered\; optional when only one)]:repo_id:"
  "*--screenshot[attach an image file to the ticket (repeatable)]:screenshot:"
)

# guard to ensure default positional specs are added only once per session
_shtab_robotsix_mill_ticket_new_defaults_added=0

_shtab_robotsix_mill_ticket_resume_blocked_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--note[operator justification, recorded as a comment\; also clears the implement stage\'s stale-spec guard when resuming into READY]:note:"
  ":id:"
)

# guard to ensure default positional specs are added only once per session
_shtab_robotsix_mill_ticket_resume_blocked_defaults_added=0

_shtab_robotsix_mill_ticket_show_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  ":id:"
)

# guard to ensure default positional specs are added only once per session
_shtab_robotsix_mill_ticket_show_defaults_added=0

_shtab_robotsix_mill_trace_health_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[output full JSON result (default\: summary)]"
)

# guard to ensure default positional specs are added only once per session
_shtab_robotsix_mill_trace_health_defaults_added=0

_shtab_robotsix_mill_trace_review_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[output raw JSON instead of human-friendly text]"
  "--repo-id[repository to run trace-review for (required if multiple repos)]:repo_id:"
)

# guard to ensure default positional specs are added only once per session
_shtab_robotsix_mill_trace_review_defaults_added=0

_shtab_robotsix_mill_verify_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--ticket-id[verify a single ticket\'s chain (default\: all tickets)]:ticket_id:"
)

# guard to ensure default positional specs are added only once per session
_shtab_robotsix_mill_verify_defaults_added=0


_shtab_robotsix_mill() {
  local context state line curcontext="$curcontext" one_or_more='(*)' remainder='(-)*' default='*::: :->robotsix-mill'

  # Add default positional/remainder specs only if none exist, and only once per session
  if (( ! _shtab_robotsix_mill_defaults_added )); then
    if (( ${_shtab_robotsix_mill_options[(I)${(q)one_or_more}*]} +          ${_shtab_robotsix_mill_options[(I)${(q)remainder}*]} +          ${_shtab_robotsix_mill_options[(I)${(q)default}]} == 0 )); then
      _shtab_robotsix_mill_options+=(': :_shtab_robotsix_mill_commands' '*::: :->robotsix-mill')
    fi
    _shtab_robotsix_mill_defaults_added=1
  fi
  _arguments -C -s $_shtab_robotsix_mill_options

  case $state in
    robotsix-mill)
      words=($line[1] "${words[@]}")
      (( CURRENT += 1 ))
      curcontext="${curcontext%:*:*}:_shtab_robotsix_mill-$line[1]:"
      case $line[1] in
        agent-check) _arguments -C -s $_shtab_robotsix_mill_agent_check_options ;;
        audit) _arguments -C -s $_shtab_robotsix_mill_audit_options ;;
        bc-check) _arguments -C -s $_shtab_robotsix_mill_bc_check_options ;;
        completeness-check) _arguments -C -s $_shtab_robotsix_mill_completeness_check_options ;;
        config-sync) _arguments -C -s $_shtab_robotsix_mill_config_sync_options ;;
        copy-paste) _arguments -C -s $_shtab_robotsix_mill_copy_paste_options ;;
        diagnostic) _arguments -C -s $_shtab_robotsix_mill_diagnostic_options ;;
        epic) _shtab_robotsix_mill_epic ;;
        forge-parity) _arguments -C -s $_shtab_robotsix_mill_forge_parity_options ;;
        health) _arguments -C -s $_shtab_robotsix_mill_health_options ;;
        inquire) _arguments -C -s $_shtab_robotsix_mill_inquire_options ;;
        langfuse-cleanup) _arguments -C -s $_shtab_robotsix_mill_langfuse_cleanup_options ;;
        member-sync) _arguments -C -s $_shtab_robotsix_mill_member_sync_options ;;
        meta) _arguments -C -s $_shtab_robotsix_mill_meta_options ;;
        module-curator) _arguments -C -s $_shtab_robotsix_mill_module_curator_options ;;
        repos) _shtab_robotsix_mill_repos ;;
        roadmap-sync) _arguments -C -s $_shtab_robotsix_mill_roadmap_sync_options ;;
        run-health) _arguments -C -s $_shtab_robotsix_mill_run_health_options ;;
        serve) _arguments -C -s $_shtab_robotsix_mill_serve_options ;;
        survey) _arguments -C -s $_shtab_robotsix_mill_survey_options ;;
        test-gap) _arguments -C -s $_shtab_robotsix_mill_test_gap_options ;;
        ticket) _shtab_robotsix_mill_ticket ;;
        trace-health) _arguments -C -s $_shtab_robotsix_mill_trace_health_options ;;
        trace-review) _arguments -C -s $_shtab_robotsix_mill_trace_review_options ;;
        verify) _arguments -C -s $_shtab_robotsix_mill_verify_options ;;
      esac
  esac
}

_shtab_robotsix_mill_epic() {
  local context state line curcontext="$curcontext" one_or_more='(*)' remainder='(-)*' default='*::: :->epic'

  # Add default positional/remainder specs only if none exist, and only once per session
  if (( ! _shtab_robotsix_mill_epic_defaults_added )); then
    if (( ${_shtab_robotsix_mill_epic_options[(I)${(q)one_or_more}*]} +          ${_shtab_robotsix_mill_epic_options[(I)${(q)remainder}*]} +          ${_shtab_robotsix_mill_epic_options[(I)${(q)default}]} == 0 )); then
      _shtab_robotsix_mill_epic_options+=(': :_shtab_robotsix_mill_epic_commands' '*::: :->epic')
    fi
    _shtab_robotsix_mill_epic_defaults_added=1
  fi
  _arguments -C -s $_shtab_robotsix_mill_epic_options

  case $state in
    epic)
      words=($line[1] "${words[@]}")
      (( CURRENT += 1 ))
      curcontext="${curcontext%:*:*}:_shtab_robotsix_mill_epic-$line[1]:"
      case $line[1] in
        new) _arguments -C -s $_shtab_robotsix_mill_epic_new_options ;;
      esac
  esac
}

_shtab_robotsix_mill_repos() {
  local context state line curcontext="$curcontext" one_or_more='(*)' remainder='(-)*' default='*::: :->repos'

  # Add default positional/remainder specs only if none exist, and only once per session
  if (( ! _shtab_robotsix_mill_repos_defaults_added )); then
    if (( ${_shtab_robotsix_mill_repos_options[(I)${(q)one_or_more}*]} +          ${_shtab_robotsix_mill_repos_options[(I)${(q)remainder}*]} +          ${_shtab_robotsix_mill_repos_options[(I)${(q)default}]} == 0 )); then
      _shtab_robotsix_mill_repos_options+=(': :_shtab_robotsix_mill_repos_commands' '*::: :->repos')
    fi
    _shtab_robotsix_mill_repos_defaults_added=1
  fi
  _arguments -C -s $_shtab_robotsix_mill_repos_options

  case $state in
    repos)
      words=($line[1] "${words[@]}")
      (( CURRENT += 1 ))
      curcontext="${curcontext%:*:*}:_shtab_robotsix_mill_repos-$line[1]:"
      case $line[1] in
        list) _arguments -C -s $_shtab_robotsix_mill_repos_list_options ;;
      esac
  esac
}

_shtab_robotsix_mill_ticket() {
  local context state line curcontext="$curcontext" one_or_more='(*)' remainder='(-)*' default='*::: :->ticket'

  # Add default positional/remainder specs only if none exist, and only once per session
  if (( ! _shtab_robotsix_mill_ticket_defaults_added )); then
    if (( ${_shtab_robotsix_mill_ticket_options[(I)${(q)one_or_more}*]} +          ${_shtab_robotsix_mill_ticket_options[(I)${(q)remainder}*]} +          ${_shtab_robotsix_mill_ticket_options[(I)${(q)default}]} == 0 )); then
      _shtab_robotsix_mill_ticket_options+=(': :_shtab_robotsix_mill_ticket_commands' '*::: :->ticket')
    fi
    _shtab_robotsix_mill_ticket_defaults_added=1
  fi
  _arguments -C -s $_shtab_robotsix_mill_ticket_options

  case $state in
    ticket)
      words=($line[1] "${words[@]}")
      (( CURRENT += 1 ))
      curcontext="${curcontext%:*:*}:_shtab_robotsix_mill_ticket-$line[1]:"
      case $line[1] in
        approve) _arguments -C -s $_shtab_robotsix_mill_ticket_approve_options ;;
        list) _arguments -C -s $_shtab_robotsix_mill_ticket_list_options ;;
        new) _arguments -C -s $_shtab_robotsix_mill_ticket_new_options ;;
        resume-blocked) _arguments -C -s $_shtab_robotsix_mill_ticket_resume_blocked_options ;;
        show) _arguments -C -s $_shtab_robotsix_mill_ticket_show_options ;;
      esac
  esac
}



typeset -A opt_args

if [[ $zsh_eval_context[-1] == eval ]]; then
  # eval/source/. command, register function for later
  compdef _shtab_robotsix_mill -N robotsix-mill
else
  # autoload from fpath, call function directly
  _shtab_robotsix_mill "$@"
fi
