# AUTOMATICALLY GENERATED by `shtab`

_shtab_robotsix_mill_subparsers=('serve' 'repos' 'ticket' 'audit' 'trace-health' 'langfuse-cleanup' 'health' 'agent-check' 'verify' 'test-gap' 'config-sync' 'member-sync' 'bc-check' 'completeness-check' 'survey' 'copy-paste' 'forge-parity' 'run-health' 'diagnostic' 'state-sync' 'env-doc-sync' 'frontend-sync' 'security-posture' 'triage-boilerplate' 'trace-review' 'roadmap-sync' 'module-curator' 'meta' 'inquire' 'epic')
_shtab_robotsix_mill_repos_subparsers=('list')
_shtab_robotsix_mill_ticket_subparsers=('new' 'list' 'show' 'approve' 'resume-blocked')
_shtab_robotsix_mill_epic_subparsers=('new')

_shtab_robotsix_mill_option_strings=('-h' '--help' '--print-completion')
_shtab_robotsix_mill_serve_option_strings=('-h' '--help' '--repo-id')
_shtab_robotsix_mill_repos_option_strings=('-h' '--help')
_shtab_robotsix_mill_repos_list_option_strings=('-h' '--help')
_shtab_robotsix_mill_ticket_option_strings=('-h' '--help')
_shtab_robotsix_mill_ticket_new_option_strings=('-h' '--help' '--title' '--description-file' '--repo-id' '--screenshot')
_shtab_robotsix_mill_ticket_list_option_strings=('-h' '--help' '--state' '--repo-id')
_shtab_robotsix_mill_ticket_show_option_strings=('-h' '--help')
_shtab_robotsix_mill_ticket_approve_option_strings=('-h' '--help')
_shtab_robotsix_mill_ticket_resume_blocked_option_strings=('-h' '--help' '--note')
_shtab_robotsix_mill_audit_option_strings=('-h' '--help' '--json')
_shtab_robotsix_mill_trace_health_option_strings=('-h' '--help' '--json')
_shtab_robotsix_mill_langfuse_cleanup_option_strings=('-h' '--help' '--json')
_shtab_robotsix_mill_health_option_strings=('-h' '--help' '--json')
_shtab_robotsix_mill_agent_check_option_strings=('-h' '--help' '--json')
_shtab_robotsix_mill_verify_option_strings=('-h' '--help' '--ticket-id')
_shtab_robotsix_mill_test_gap_option_strings=('-h' '--help' '--json')
_shtab_robotsix_mill_config_sync_option_strings=('-h' '--help' '--json')
_shtab_robotsix_mill_member_sync_option_strings=('-h' '--help' '--json' '--repo-id')
_shtab_robotsix_mill_bc_check_option_strings=('-h' '--help' '--json')
_shtab_robotsix_mill_completeness_check_option_strings=('-h' '--help' '--json')
_shtab_robotsix_mill_survey_option_strings=('-h' '--help' '--json')
_shtab_robotsix_mill_copy_paste_option_strings=('-h' '--help' '--json')
_shtab_robotsix_mill_forge_parity_option_strings=('-h' '--help' '--json')
_shtab_robotsix_mill_run_health_option_strings=('-h' '--help' '--json')
_shtab_robotsix_mill_diagnostic_option_strings=('-h' '--help' '--json')
_shtab_robotsix_mill_state_sync_option_strings=('-h' '--help' '--json')
_shtab_robotsix_mill_env_doc_sync_option_strings=('-h' '--help' '--json')
_shtab_robotsix_mill_frontend_sync_option_strings=('-h' '--help' '--json')
_shtab_robotsix_mill_security_posture_option_strings=('-h' '--help' '--json')
_shtab_robotsix_mill_triage_boilerplate_option_strings=('-h' '--help' '--json')
_shtab_robotsix_mill_trace_review_option_strings=('-h' '--help' '--json' '--repo-id')
_shtab_robotsix_mill_roadmap_sync_option_strings=('-h' '--help' '--json' '--repo-id')
_shtab_robotsix_mill_module_curator_option_strings=('-h' '--help' '--json')
_shtab_robotsix_mill_meta_option_strings=('-h' '--help' '--json')
_shtab_robotsix_mill_inquire_option_strings=('-h' '--help' '--title' '--description-file')
_shtab_robotsix_mill_epic_option_strings=('-h' '--help')
_shtab_robotsix_mill_epic_new_option_strings=('-h' '--help' '--title' '--description-file' '--repo-id')



_shtab_robotsix_mill_pos_0_choices=('serve' 'repos' 'ticket' 'audit' 'trace-health' 'langfuse-cleanup' 'health' 'agent-check' 'verify' 'test-gap' 'config-sync' 'member-sync' 'bc-check' 'completeness-check' 'survey' 'copy-paste' 'forge-parity' 'run-health' 'diagnostic' 'state-sync' 'env-doc-sync' 'frontend-sync' 'security-posture' 'triage-boilerplate' 'trace-review' 'roadmap-sync' 'module-curator' 'meta' 'inquire' 'epic')
_shtab_robotsix_mill___print_completion_choices=('bash' 'zsh' 'tcsh')
_shtab_robotsix_mill_repos_pos_0_choices=('list')
_shtab_robotsix_mill_ticket_pos_0_choices=('new' 'list' 'show' 'approve' 'resume-blocked')
_shtab_robotsix_mill_ticket_list___state_choices=('draft' 'human_issue_approval' 'ready' 'documenting' 'code_review' 'deliverable' 'human_mr_approval' 'implement_complete' 'waiting_auto_merge' 'rebasing' 'fixing_ci' 'addressing_review' 'done' 'closed' 'errored' 'blocked' 'asked' 'answered' 'awaiting_user_reply' 'epic_open' 'epic_closed')
_shtab_robotsix_mill_epic_pos_0_choices=('new')

_shtab_robotsix_mill_pos_0_nargs=A...
_shtab_robotsix_mill__h_nargs=0
_shtab_robotsix_mill___help_nargs=0
_shtab_robotsix_mill_serve__h_nargs=0
_shtab_robotsix_mill_serve___help_nargs=0
_shtab_robotsix_mill_repos_pos_0_nargs=A...
_shtab_robotsix_mill_repos__h_nargs=0
_shtab_robotsix_mill_repos___help_nargs=0
_shtab_robotsix_mill_repos_list__h_nargs=0
_shtab_robotsix_mill_repos_list___help_nargs=0
_shtab_robotsix_mill_ticket_pos_0_nargs=A...
_shtab_robotsix_mill_ticket__h_nargs=0
_shtab_robotsix_mill_ticket___help_nargs=0
_shtab_robotsix_mill_ticket_new__h_nargs=0
_shtab_robotsix_mill_ticket_new___help_nargs=0
_shtab_robotsix_mill_ticket_list__h_nargs=0
_shtab_robotsix_mill_ticket_list___help_nargs=0
_shtab_robotsix_mill_ticket_show__h_nargs=0
_shtab_robotsix_mill_ticket_show___help_nargs=0
_shtab_robotsix_mill_ticket_approve__h_nargs=0
_shtab_robotsix_mill_ticket_approve___help_nargs=0
_shtab_robotsix_mill_ticket_resume_blocked__h_nargs=0
_shtab_robotsix_mill_ticket_resume_blocked___help_nargs=0
_shtab_robotsix_mill_audit__h_nargs=0
_shtab_robotsix_mill_audit___help_nargs=0
_shtab_robotsix_mill_audit___json_nargs=0
_shtab_robotsix_mill_trace_health__h_nargs=0
_shtab_robotsix_mill_trace_health___help_nargs=0
_shtab_robotsix_mill_trace_health___json_nargs=0
_shtab_robotsix_mill_langfuse_cleanup__h_nargs=0
_shtab_robotsix_mill_langfuse_cleanup___help_nargs=0
_shtab_robotsix_mill_langfuse_cleanup___json_nargs=0
_shtab_robotsix_mill_health__h_nargs=0
_shtab_robotsix_mill_health___help_nargs=0
_shtab_robotsix_mill_health___json_nargs=0
_shtab_robotsix_mill_agent_check__h_nargs=0
_shtab_robotsix_mill_agent_check___help_nargs=0
_shtab_robotsix_mill_agent_check___json_nargs=0
_shtab_robotsix_mill_verify__h_nargs=0
_shtab_robotsix_mill_verify___help_nargs=0
_shtab_robotsix_mill_test_gap__h_nargs=0
_shtab_robotsix_mill_test_gap___help_nargs=0
_shtab_robotsix_mill_test_gap___json_nargs=0
_shtab_robotsix_mill_config_sync__h_nargs=0
_shtab_robotsix_mill_config_sync___help_nargs=0
_shtab_robotsix_mill_config_sync___json_nargs=0
_shtab_robotsix_mill_member_sync__h_nargs=0
_shtab_robotsix_mill_member_sync___help_nargs=0
_shtab_robotsix_mill_member_sync___json_nargs=0
_shtab_robotsix_mill_bc_check__h_nargs=0
_shtab_robotsix_mill_bc_check___help_nargs=0
_shtab_robotsix_mill_bc_check___json_nargs=0
_shtab_robotsix_mill_completeness_check__h_nargs=0
_shtab_robotsix_mill_completeness_check___help_nargs=0
_shtab_robotsix_mill_completeness_check___json_nargs=0
_shtab_robotsix_mill_survey__h_nargs=0
_shtab_robotsix_mill_survey___help_nargs=0
_shtab_robotsix_mill_survey___json_nargs=0
_shtab_robotsix_mill_copy_paste__h_nargs=0
_shtab_robotsix_mill_copy_paste___help_nargs=0
_shtab_robotsix_mill_copy_paste___json_nargs=0
_shtab_robotsix_mill_forge_parity__h_nargs=0
_shtab_robotsix_mill_forge_parity___help_nargs=0
_shtab_robotsix_mill_forge_parity___json_nargs=0
_shtab_robotsix_mill_run_health__h_nargs=0
_shtab_robotsix_mill_run_health___help_nargs=0
_shtab_robotsix_mill_run_health___json_nargs=0
_shtab_robotsix_mill_diagnostic__h_nargs=0
_shtab_robotsix_mill_diagnostic___help_nargs=0
_shtab_robotsix_mill_diagnostic___json_nargs=0
_shtab_robotsix_mill_state_sync__h_nargs=0
_shtab_robotsix_mill_state_sync___help_nargs=0
_shtab_robotsix_mill_state_sync___json_nargs=0
_shtab_robotsix_mill_env_doc_sync__h_nargs=0
_shtab_robotsix_mill_env_doc_sync___help_nargs=0
_shtab_robotsix_mill_env_doc_sync___json_nargs=0
_shtab_robotsix_mill_frontend_sync__h_nargs=0
_shtab_robotsix_mill_frontend_sync___help_nargs=0
_shtab_robotsix_mill_frontend_sync___json_nargs=0
_shtab_robotsix_mill_security_posture__h_nargs=0
_shtab_robotsix_mill_security_posture___help_nargs=0
_shtab_robotsix_mill_security_posture___json_nargs=0
_shtab_robotsix_mill_triage_boilerplate__h_nargs=0
_shtab_robotsix_mill_triage_boilerplate___help_nargs=0
_shtab_robotsix_mill_triage_boilerplate___json_nargs=0
_shtab_robotsix_mill_trace_review__h_nargs=0
_shtab_robotsix_mill_trace_review___help_nargs=0
_shtab_robotsix_mill_trace_review___json_nargs=0
_shtab_robotsix_mill_roadmap_sync__h_nargs=0
_shtab_robotsix_mill_roadmap_sync___help_nargs=0
_shtab_robotsix_mill_roadmap_sync___json_nargs=0
_shtab_robotsix_mill_module_curator__h_nargs=0
_shtab_robotsix_mill_module_curator___help_nargs=0
_shtab_robotsix_mill_module_curator___json_nargs=0
_shtab_robotsix_mill_meta__h_nargs=0
_shtab_robotsix_mill_meta___help_nargs=0
_shtab_robotsix_mill_meta___json_nargs=0
_shtab_robotsix_mill_inquire__h_nargs=0
_shtab_robotsix_mill_inquire___help_nargs=0
_shtab_robotsix_mill_epic_pos_0_nargs=A...
_shtab_robotsix_mill_epic__h_nargs=0
_shtab_robotsix_mill_epic___help_nargs=0
_shtab_robotsix_mill_epic_new__h_nargs=0
_shtab_robotsix_mill_epic_new___help_nargs=0


# $1=COMP_WORDS[1]
_shtab_compgen_files() {
  compgen -f -- $1  # files
}

# $1=COMP_WORDS[1]
_shtab_compgen_dirs() {
  compgen -d -- $1  # recurse into subdirs
}

# $1=COMP_WORDS[1]
_shtab_replace_nonword() {
  echo "${1//[^[:word:]]/_}"
}

# set default values (called for the initial parser & any subparsers)
_set_parser_defaults() {
  local subparsers_var="${prefix}_subparsers[@]"
  sub_parsers=${!subparsers_var-}

  local current_option_strings_var="${prefix}_option_strings[@]"
  current_option_strings=${!current_option_strings_var}

  completed_positional_actions=0

  _set_new_action "pos_${completed_positional_actions}" true
}

# $1=action identifier
# $2=positional action (bool)
# set all identifiers for an action's parameters
_set_new_action() {
  current_action="${prefix}_$(_shtab_replace_nonword $1)"

  local current_action_compgen_var=${current_action}_COMPGEN
  current_action_compgen="${!current_action_compgen_var-}"

  local current_action_choices_var="${current_action}_choices[@]"
  current_action_choices="${!current_action_choices_var-}"

  local current_action_nargs_var="${current_action}_nargs"
  if [ -n "${!current_action_nargs_var-}" ]; then
    current_action_nargs="${!current_action_nargs_var}"
  else
    current_action_nargs=1
  fi

  current_action_args_start_index=$(( $word_index + 1 - $pos_only ))

  current_action_is_positional=$2
}

# Notes:
# `COMPREPLY`: what will be rendered after completion is triggered
# `completing_word`: currently typed word to generate completions for
# `${!var}`: evaluates the content of `var` and expand its content as a variable
#     hello="world"
#     x="hello"
#     ${!x} -> ${hello} -> "world"
_shtab_robotsix_mill() {
  local completing_word="${COMP_WORDS[COMP_CWORD]}"
  local previous_word="${COMP_WORDS[COMP_CWORD-1]}"
  local completed_positional_actions
  local current_action
  local current_action_args_start_index
  local current_action_choices
  local current_action_compgen
  local current_action_is_positional
  local current_action_nargs
  local current_option_strings
  local sub_parsers
  COMPREPLY=()

  local prefix=_shtab_robotsix_mill
  local word_index=0
  local pos_only=0 # "--" delimeter not encountered yet
  _set_parser_defaults
  word_index=1

  # determine what arguments are appropriate for the current state
  # of the arg parser
  while [ $word_index -ne $COMP_CWORD ]; do
    local this_word="${COMP_WORDS[$word_index]}"

    if [[ $pos_only = 1 || " $this_word " != " -- " ]]; then
      if [[ -n $sub_parsers && " ${sub_parsers[@]} " == *" ${this_word} "* ]]; then
        # valid subcommand: add it to the prefix & reset the current action
        prefix="${prefix}_$(_shtab_replace_nonword $this_word)"
        _set_parser_defaults
      fi

      if [[ " ${current_option_strings[@]} " == *" ${this_word} "* ]]; then
        # a new action should be acquired (due to recognised option string or
        # no more input expected from current action);
        # the next positional action can fill in here
        _set_new_action $this_word false
      fi

      if [[ "$current_action_nargs" != "*" ]] && \
         [[ "$current_action_nargs" != "+" ]] && \
         [[ "$current_action_nargs" != "?" ]] && \
         [[ "$current_action_nargs" != *"..." ]] && \
         (( $word_index + 1 - $current_action_args_start_index - $pos_only >= \
            $current_action_nargs )); then
        $current_action_is_positional && let "completed_positional_actions += 1"
        _set_new_action "pos_${completed_positional_actions}" true
      fi
    else
      pos_only=1 # "--" delimeter encountered
    fi

    let "word_index+=1"
  done

  # Generate the completions

  if [[ $pos_only = 0 && "${completing_word}" == -* ]]; then
    # optional argument started: use option strings
    COMPREPLY=( $(compgen -W "${current_option_strings[*]}" -- "${completing_word}") )
  elif [[ "${previous_word}" == ">" || "${previous_word}" == ">>" ||
          "${previous_word}" =~ ^[12]">" || "${previous_word}" =~ ^[12]">>" ]]; then
    # handle redirection operators
    COMPREPLY=( $(compgen -f -- "${completing_word}") )
  else
    # use choices & compgen
    local IFS=$'\n' # items may contain spaces, so delimit using newline
    COMPREPLY=( $([ -n "${current_action_compgen}" ] \
                  && "${current_action_compgen}" "${completing_word}") )
    unset IFS
    COMPREPLY+=( $(compgen -W "${current_action_choices[*]}" -- "${completing_word}") )
  fi

  return 0
}

complete -o filenames -F _shtab_robotsix_mill robotsix-mill